### PR TITLE
started with wildcards

### PR DESCRIPTION
**Pull request by PaulicStudios**

### CODE REVIEW

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2636
Failed: 148

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2634
Failed: 150

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2632
Failed: 152

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2632
Failed: 152

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2634
Failed: 150

**Comment by PaulicStudios** [comment]
@JonasGoetz01 hab die wildcard Funktion fertig geschrieben: `char	**ft_expand_wildcard(char *str)`
Die nimmt ein arg wie t*.c und returned dann eine array wie ft_split mit allen filenamen

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2646
Failed: 138

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2648
Failed: 136

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2647
Failed: 137

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2650
Failed: 134

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2648
Failed: 136

**Comment by JonasGoetz01** [comment]
## Test Summary

Total tests: 2784
Passed: 2647
Failed: 137

**Pull request merged**
